import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/ssr';
import express from 'express';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import bootstrap from './src/main.server';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');
  const indexHtml = join(serverDistFolder, 'index.server.html');

  const commonEngine = new CommonEngine();

  server.set('view engine', 'html');
  server.set('views', browserDistFolder);

  /**
   * Static files generated by Angular.
   *
   * Since the application runs under /site, all browser files are served
   * from this path. The index file is disabled here because SSR should
   * handle application routes.
   */
  server.use('/site', express.static(browserDistFolder, {
    maxAge: '1y',
    index: false
  }));
    

  /**
   * Redirect root domain to /site/.
   */
  server.get('/', (_req, res) => {
    res.redirect(301, '/site/');
  });

  /**
   * Normalize /site to /site/.
   */
  /*
  server.get('/site', (_req, res) => {
    res.redirect(301, '/site/');
  });  
  */

  /**
   * All regular /site routes use the Angular SSR engine.
   */
  server.get('/site/*', (req, res, next) => {
    const { protocol, originalUrl, headers } = req;

    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: '/site/' }],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(Number(port), () => {
    console.log(`Node Express server listening on port ${port}`);
  });
}

run();
